import { NextRequest, NextResponse } from 'next/server';
import { createAdminClient } from '@/lib/supabase-admin';
import { validateBody } from '@/lib/schemas/validate';
import { inscriptionSchema } from '@/lib/schemas/inscription';
import { checkInscriptionRateLimit } from '@/lib/rate-limit/inscription-rate-limit';
import { notifyNewInscription } from '@/lib/notifications/whatsapp-notif';

function getIp(request: NextRequest): string {
  return (
    request.headers.get('x-forwarded-for')?.split(',')[0]?.trim() ??
    request.headers.get('x-real-ip') ??
    'anonymous'
  );
}

export async function POST(request: NextRequest) {
  // 1. Rate limit: 3 inscriptions / IP / hour
  const ip = getIp(request);
  const rl = checkInscriptionRateLimit(ip);
  if (!rl.ok) {
    return NextResponse.json(
      { error: 'Trop de tentatives. Réessayez dans 1 heure.' },
      { status: 429, headers: { 'Retry-After': String(rl.resetIn) } },
    );
  }

  // 2. Parse & validate body
  let rawBody: unknown;
  try {
    rawBody = await request.json();
  } catch {
    return NextResponse.json({ error: 'JSON invalide' }, { status: 400 });
  }

  const { data: body, error: validationError } = validateBody(inscriptionSchema, rawBody);
  if (validationError) return validationError;

  // Honeypot check — if website field is non-empty, silently reject
  if (body.website && body.website.length > 0) {
    return NextResponse.json({ ok: true, redirect: `/inscription/success?email=${encodeURIComponent(body.email)}` });
  }

  const admin = createAdminClient();

  // 4. Atomic creation: auth.users + profiles + boutiques + inscriptions_metadata
  let userId: string | null = null;

  try {
    // 4a. Create auth user
    const { data: authData, error: signUpError } = await admin.auth.admin.createUser({
      email: body.email,
      password: body.password,
      email_confirm: false, // Supabase will send confirmation email
    });

    if (signUpError || !authData?.user) {
      const message = signUpError?.message ?? 'Erreur création compte';
      // Handle duplicate email
      if (signUpError?.message?.toLowerCase().includes('already registered') ||
          signUpError?.message?.toLowerCase().includes('already been registered') ||
          signUpError?.message?.toLowerCase().includes('email address is already')) {
        return NextResponse.json(
          { error: 'Cet email est déjà utilisé. Connectez-vous ou utilisez un autre email.' },
          { status: 409 },
        );
      }
      throw new Error(message);
    }

    userId = authData.user.id;

    // 4b. Insert profile (proprietaire)
    const { error: proprietaireError } = await admin
      .from('profiles')
      .insert({
        id: userId,
        nom_complet: body.nom_complet.trim(),
        telephone: body.telephone_whatsapp,
        role: 'proprio' as const,
      });

    if (proprietaireError) {
      throw new Error(`Erreur création profil: ${proprietaireError.message}`);
    }

    // 4c. Insert boutique (slug auto-generated by DB trigger, leave as null)
    const codeUnique = `MF-${userId.slice(0, 8).toUpperCase()}`;
    const { error: boutiqueError } = await admin
      .from('boutiques')
      .insert({
        proprietaire_id: userId,
        nom: body.boutique_nom.trim(),
        ville: body.boutique_zone.trim(),
        quartier: null,
        zone: body.boutique_zone.trim(),
        telephone_whatsapp: body.telephone_whatsapp,
        actif: true,
        est_actif: true,
        couleur: '#00C853',
        couleur_theme: '#00C853',
        code_unique: codeUnique,
        pin_caisse: '0000',
      });

    if (boutiqueError) {
      throw new Error(`Erreur création boutique: ${boutiqueError.message}`);
    }

    // 4d. Insert inscriptions_metadata (non-blocking — best effort)
    void admin
      .from('inscriptions_metadata')
      .insert({
        user_id: userId,
        comment_connu: body.comment_connu ?? null,
        ip_address: ip === 'anonymous' ? null : ip,
        user_agent: request.headers.get('user-agent') ?? null,
      })
      .then(({ error }) => {
        if (error) console.warn('[INSCRIPTION] metadata insert failed:', error.message);
      });
  } catch (err) {
    // Rollback: delete auth user if created
    if (userId) {
      await admin.auth.admin.deleteUser(userId).catch((e) => {
        console.error('[INSCRIPTION] rollback deleteUser failed:', e);
      });
    }
    const message = err instanceof Error ? err.message : 'Erreur serveur';
    return NextResponse.json({ error: message }, { status: 500 });
  }

  // 5. Notify super admin
  notifyNewInscription({
    nom: body.nom_complet,
    boutique_nom: body.boutique_nom,
    boutique_zone: body.boutique_zone,
    email: body.email,
    telephone_whatsapp: body.telephone_whatsapp,
    comment_connu: body.comment_connu,
  });

  // 6. Return success redirect
  return NextResponse.json({
    ok: true,
    redirect: `/inscription/success?email=${encodeURIComponent(body.email)}`,
  });
}
