/**
 * GET /api/caisse/terminals
 *
 * Returns the list of known POS terminals for the authenticated boutique.
 * Requires a valid caisse session token in the `x-caisse-token` header.
 *
 * Response 200: { terminals: CaisseTerminal[] }
 * Response 401/403: { error: string }
 *
 * Each terminal record includes:
 *   - terminal_id   – stable UUID generated by the client browser
 *   - label         – optional human-readable name (settable in a future iteration)
 *   - first_seen_at – when the terminal first authenticated
 *   - last_seen_at  – when the terminal last authenticated
 *   - last_ip       – last IP address seen (may be null)
 *   - statut        – 'actif' | 'revoque'
 *
 * Note: terminal revocation (PATCH) is intentionally left for a subsequent
 * iteration.  The `statut` column is already in place — a future endpoint
 * will allow boutique owners to set it to 'revoque' via the dashboard.
 */

import { NextRequest, NextResponse } from 'next/server';
import { createAdminClient } from '@/lib/supabase-admin';
import { requireCaisseSession } from '@/lib/requireCaisseSession';

export async function GET(request: NextRequest) {
  const guard = requireCaisseSession(request);
  if ('response' in guard) return guard.response;

  const { boutique_id } = guard.context;
  const admin = createAdminClient();

  const { data: terminals, error } = await admin
    .from('caisse_terminals')
    .select('id, terminal_id, label, first_seen_at, last_seen_at, last_ip, statut')
    .eq('boutique_id', boutique_id)
    .order('last_seen_at', { ascending: false });

  if (error) {
    console.error('[caisse/terminals] fetch_error', { boutique_id, error: error.message });
    return NextResponse.json({ error: 'Erreur lors de la récupération des terminaux' }, { status: 500 });
  }

  return NextResponse.json({ terminals: terminals ?? [] });
}
